#!/bin/bash
#
# This script is intended to autoscan all DVB services and produce text dump
# output of the details found
#
# Currently only DVB-T

SCRIPTDIR=$(dirname $0)

MULTIPLEXES=$(cat channels.conf | cut -d: -f1 |sort |uniq)

LOGFILE=autoscan.log
>$LOGFILE

tzap_start() {
	local CHANNEL="$1"

	echo LOG tzap_start $CHANNEL >>$LOGFILE
	tzap -c channels.conf $CHANNEL >>$LOGFILE 2>&1 &
	TZAP_PID=$!
	sleep 5s
}

tzap_stop() {
	echo LOG tzap_stop >>$LOGFILE
	kill $TZAP_PID
	wait $TZAP_PID
}

dump_pid() {
	local CHANNEL="$1"
	local PID="$2"
	if [ -n "$3" ]; then
		local NAME=".$3"
	fi

	echo LOG dump_pid $CHANNEL $PID $NAME >>$LOGFILE
	OUT=scan.${CHANNEL}.pid${PID}${NAME}
	dvbsnoop $PID -timeout 10000 -tn -nohexdumpbuffer -n 1 -crc >$OUT

	# Remove CRC as it will change every single time
	perl -p -i -e 's/^CRC: \d+ \(0x[0-9A-Fa-f]+\)/CRC: __REMOVED__/' $OUT

	# Version number is interesting to note, but ultimately useless
	perl -p -i -e 's/^Version_number: \d+ \(0x[0-9A-Fa-f]+\)/Version_number: __REMOVED__/' $OUT
}

scan_one() {
	local CHANNEL="$1"

	# TODO - dump a processed feinfo ??

	dvbsnoop -s pidscan |
		sed -e '
			s/\(SECTION: DSM-CC\) - .*/\1 ...\]/;
			s/\(SECTION: Event Information Table (EIT)\) - .*/\1 ...\]/;
			s/\(SECTION: Time\) .*/\1 ...\]/;
		' >scan.${CHANNEL}.pidscan

	dump_pid $CHANNEL 0x0000 PAT
	dump_pid $CHANNEL 0x0001 CAT
	dump_pid $CHANNEL 0x0010 NIT
	dump_pid $CHANNEL 0x0011 SDT
	#dump_pid $CHANNEL 0x0015

	# scan the program pids
	PMTS=`grep Program_map_PID scan.${CHANNEL}.pid0x0000.PAT | cut -d"(" -f2 | cut -d")" -f1`
	for i in $PMTS; do
		dump_pid $CHANNEL $i PMT

		# TODO - read the PMT files and generate a channel PID list
	done

	$SCRIPTDIR/summarise_dvbsnoop scan.${CHANNEL}.pid* >scan.${CHANNEL}.summary
}

multiplex() {
	local i="$1"
	echo TRY $i
	tzap_start ${i}
	scan_one $i
	tzap_stop
}

killall tzap >/dev/null

if [ -n "$1" ]; then
	multiplex "$1"
	exit
fi

for i in $MULTIPLEXES; do
	multiplex "$i"
done

# Now get a slightly different view of things from the newer dvbv5 tools
dvbv5-scan channels.dvbv5 -o channels.tmp
$SCRIPTDIR/inisort channels.tmp >channels.dvbv5.out
rm channels.tmp
