#!/bin/bash
#
# This script is intended to autoscan all DVB services and produce text dump
# output of the details found
#
# Currently only DVB-T

MULTIPLEXES=$(cat channels.conf | cut -d: -f1 |sort |uniq)

LOGFILE=autoscan.log
>$LOGFILE

multiplex() {
	local i="$1"
	echo TRY $i
	/home/hamish/s/src/xmltv/autoscan/summarise_dvbsnoop scan.${i}.pid* >scan.${i}.summary
}

if [ -n "$1" ]; then
	multiplex "$1"
	exit
fi

for i in $MULTIPLEXES; do
	multiplex "$i"
done

